name: Java CI with Gradle

on:
  push:
    branches: [ "main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # ✅ 공통 application-common.yml, ci.yml 생성
    - run: |
        touch ./src/main/resources/application-common.yml
        echo -e "${{ secrets.COMMON_YML }}" > ./hack/src/main/resources/application-common.yml

    # ✅ 환경별 application-main.yml 또는 application-dev.yml 설정
    - run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          touch ./src/main/resources/application-main.yml
          echo "${{ secrets.MAIN_YML }}" > ./hack/src/main/resources/application-main.yml
        else
          echo "${{ secrets.DEV_YML }}" > ./hack/src/main/resources/application-dev.yml
        fi

    - name: Set Gradle Wrapper executable permission
      run: chmod +x ./gradlew
      
    - name: Run tests with CI profile
      run: ./gradlew test -Dspring.profiles.active=test,common

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Copy to DEV EC2
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEV_EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.DEV_EC2_PEM }}
        port: 22
        source: ./build/libs/*.jar
        target: /home/ubuntu/cicd
        strip_components: 2
    - name: Copy to MAIN EC2
      if: github.ref == 'refs/heads/master'
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.MAIN_EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.MAIN_EC2_PEM }}
        port: 22
        source: ./build/libs/*.jar
        target: /home/ubuntu/cicd
        strip_components: 2
    
    # ✅ main 브랜치: MAIN 서버에 스크립트 복사 및 실행
    - name: Copy deploy script file to MAIN EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@v0.1.4
      with:
        username: ${{ secrets.EC2_USERNAME }}
        host: ${{ secrets.MAIN_EC2_HOST }}
        key: ${{ secrets.MAIN_EC2_PEM }}
        source: ".github/workflows/deploy_main.sh"
        target: "/home/ubuntu/cicd"
        strip_components: 2
    
    - name: Execute deploy script on MAIN EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v0.1.10
      with:
        username: ${{ secrets.EC2_USERNAME }}
        host: ${{ secrets.MAIN_EC2_HOST }}
        key: ${{ secrets.MAIN_EC2_PEM }}
        script_stop: true
        script: |
          chmod +x /home/ubuntu/cicd/deploy_main.sh
          sh /home/ubuntu/cicd/deploy_main.sh
